vim.opt.backup = false            -- creates a backup file
vim.opt.clipboard = "unnamedplus" -- allows neovim to access the system clipboard
vim.opt.conceallevel = 0          -- so that `` is visible in markdown files
vim.opt.fileencoding = "utf-8"    -- the encoding written to a file
vim.opt.hlsearch = true           -- highlight all matches on previous search pattern
vim.opt.ignorecase = true         -- ignore case in search patterns
vim.opt.showmode = false          -- we don't need to see things like -- INSERT --
vim.opt.showtabline = 1           -- always show tabs?
vim.opt.smartcase = true          -- smart case
vim.opt.smartindent = true        -- make indenting smarter again
vim.opt.splitbelow = true         -- force horizontal splits below current window
vim.opt.splitright = true         -- force vertical splits to the right of curr window
vim.opt.swapfile = false          -- creates a swapfile
vim.opt.termguicolors = true      -- set term gui colors (most terminals support this)
vim.opt.undofile = true           -- enable persistent undo
vim.opt.expandtab = true          -- convert tabs to spaces
vim.opt.tabstop = 4               -- numbef of spaces for a tab
vim.opt.shiftwidth = 4            -- number of spaces inserted for each indentation
vim.opt.cursorline = true         -- highlight the current line
vim.opt.number = true             -- set numbered lines
vim.opt.showcmd = false           -- hide (partial) command in the last line of the screen (for performance)
vim.opt.ruler = false             -- hide line and col number of the cursor position
vim.opt.numberwidth = 4           -- min num of columns for the line number
vim.opt.wrap = false              -- display lines as one long line
vim.opt.scrolloff = 8             -- min num of screen lines above and below cursor
vim.opt.sidescrolloff = 8         -- min num of screen cols left and right of cursor
vim.opt.iskeyword:append "-"      -- treats words with `-` as single words
vim.opt.linebreak = true
