# -*- mode: ruby -*-

tap "anomalyco/tap"

brew "age"
brew "bash"
brew "bash-completion@2"
brew "chezmoi"
brew "coreutils"
brew "curl"
brew "direnv"
brew "findutils"
brew "fzf"
brew "gh"
brew "git"
brew "gnu-sed"
brew "gnu-tar"
brew "gnupg"
brew "grep"
brew "hcloud"
brew "htop"
brew "jq"
brew "lua"
brew "make"
brew "moreutils"
brew "node"
brew "openssh"
brew "p7zip"
brew "pyenv"
brew "pyenv-virtualenv"
brew "ripgrep"
brew "rsync"
brew "shellcheck"
brew "tldr"
brew "tmux"
brew "tree"
brew "uv"
brew "vim-classic"
brew "watch"
brew "anomalyco/tap/opencode", trusted: true
brew "zoxide"
brew "zsh"

cask "balenaetcher"
cask "chatgpt"
cask "claude-code"
cask "font-jetbrains-mono"
cask "freeplane"
cask "ghostty"
cask "hyperkey"
cask "maccy"
cask "obsidian"
cask "orbstack"
cask "raspberry-pi-imager"
cask "rectangle"
